apiVersion: v1
kind: Secret
metadata:
  name: qube-quant-secrets
  namespace: qube-quant
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "stocks"
  DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres:5432/stocks"
